import type { SscChapter, SscIctConfig, SscMcq, SscShortQuestion } from './types';
import { chapterOneUpgrade } from './chapter1-upgrade';
import { chapterTwoUpgrade } from './chapter2-upgrade';
import { chapterThreeUpgrade } from './chapter3-upgrade';
import { chapterFourUpgrade } from './chapter4-upgrade';
import { chapterFiveUpgrade } from './chapter5-upgrade';
import { chapterSixUpgrade } from './chapter6-upgrade';

const makeMcq = (
  id: string,
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  difficulty: SscMcq['difficulty'] = 'Medium'
): SscMcq => ({
  id,
  question,
  options,
  correctIndex,
  explanation,
  difficulty,
  isPublished: true,
});

const makeShort = (
  id: string,
  question: string,
  answer: string,
  importance: SscShortQuestion['importance'] = 'Medium'
): SscShortQuestion => ({
  id,
  question,
  answer,
  importance,
  isPublished: true,
});

export const defaultSscChapters: SscChapter[] = [
  {
    id: 'ssc-chapter-1',
    title: 'তথ্য ও যোগাযোগ প্রযুক্তি ও আমাদের বাংলাদেশ',
    slug: 'ict-and-bangladesh',
    description: 'ডিজিটাল বাংলাদেশ, ই-সেবা, তথ্যপ্রযুক্তির ব্যবহার এবং নাগরিক জীবনে ICT-এর প্রভাব।',
    price: 100,
    orderIndex: 1,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 01 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'তথ্য ও যোগাযোগ প্রযুক্তি হলো তথ্য সংগ্রহ, সংরক্ষণ, প্রক্রিয়াকরণ এবং আদান-প্রদানের জন্য ব্যবহৃত প্রযুক্তির সমন্বয়। SSC ICT-তে এই অধ্যায়টি ভিত্তি তৈরি করে।',
      'ডিজিটাল বাংলাদেশ ধারণার মূল লক্ষ্য হলো সরকারি ও বেসরকারি সেবা দ্রুত, স্বচ্ছ এবং সহজলভ্য করা। ই-সেবা, অনলাইন শিক্ষা, টেলিমেডিসিন এবং মোবাইল ব্যাংকিং এর বাস্তব উদাহরণ।',
      'ICT ব্যবহারে সময় ও খরচ কমে, তথ্যপ্রাপ্তি সহজ হয়, কর্মসংস্থানের নতুন ক্ষেত্র তৈরি হয় এবং প্রশাসনিক দক্ষতা বাড়ে।',
      'ঝুঁকি কমাতে তথ্যের নিরাপত্তা, নৈতিক ব্যবহার, সাইবার সচেতনতা এবং নির্ভরযোগ্য উৎস যাচাই করা জরুরি।',
    ],
    mcqs: [
      makeMcq('ssc-c1-q1', 'ICT-এর পূর্ণরূপ কী?', ['Information and Communication Technology', 'Internet Control Tool', 'Input Communication Task', 'Integrated Computer Training'], 0, 'ICT অর্থ Information and Communication Technology.'),
      makeMcq('ssc-c1-q2', 'ই-গভর্নেন্সের প্রধান সুবিধা কোনটি?', ['সেবা ধীর করা', 'সেবা সহজ ও স্বচ্ছ করা', 'কাগজের ব্যবহার বাড়ানো', 'ইন্টারনেট বন্ধ করা'], 1, 'ই-গভর্নেন্স নাগরিক সেবা দ্রুত ও স্বচ্ছ করে।'),
      makeMcq('ssc-c1-q3', 'টেলিমেডিসিন কোন ক্ষেত্রে ICT-এর ব্যবহার?', ['চিকিৎসা', 'কৃষি', 'বিনোদন', 'পরিবহন'], 0, 'দূর থেকে চিকিৎসা পরামর্শ দেওয়াকে টেলিমেডিসিন বলা হয়।'),
      makeMcq('ssc-c1-q4', 'ডিজিটাল কনটেন্ট বলতে কী বোঝায়?', ['কাগজের বই', 'অনলাইনে ব্যবহৃত লেখা/ছবি/ভিডিও', 'শুধু প্রিন্টার', 'শুধু বিদ্যুৎ'], 1, 'ডিজিটাল কনটেন্ট ইলেকট্রনিক মাধ্যমে ব্যবহারযোগ্য তথ্য।', 'Easy'),
      makeMcq('ssc-c1-q5', 'ICT ব্যবহারে কোন দক্ষতা সবচেয়ে গুরুত্বপূর্ণ?', ['সাইবার সচেতনতা', 'অপ্রয়োজনীয় পোস্ট', 'পাসওয়ার্ড শেয়ার', 'ভুয়া তথ্য ছড়ানো'], 0, 'নিরাপদ ও দায়িত্বশীল ব্যবহার ICT শেখার গুরুত্বপূর্ণ অংশ।'),
      makeMcq('ssc-c1-q6', 'অনলাইন শিক্ষা কোন ধরনের সেবা?', ['ই-লার্নিং', 'ই-কমার্স', 'ই-মেইল', 'ই-পেপার'], 0, 'ইন্টারনেটভিত্তিক শিক্ষা কার্যক্রমকে ই-লার্নিং বলা হয়।'),
    ],
    shortQuestions: [
      makeShort('ssc-c1-s1', 'ডিজিটাল বাংলাদেশ কী?', 'ICT ব্যবহার করে নাগরিক সেবা, শিক্ষা, স্বাস্থ্য, অর্থনীতি ও প্রশাসনকে আধুনিক এবং সহজলভ্য করার ধারণা।', 'High'),
      makeShort('ssc-c1-s2', 'ই-সেবার দুটি উদাহরণ দাও।', 'অনলাইন জন্ম নিবন্ধন, অনলাইন ভর্তি, মোবাইল ব্যাংকিং, টেলিমেডিসিন ইত্যাদি।'),
      makeShort('ssc-c1-s3', 'ICT ব্যবহারে সতর্কতা কেন জরুরি?', 'ব্যক্তিগত তথ্য, পাসওয়ার্ড এবং অনলাইন আচরণ নিরাপদ রাখতে সতর্কতা জরুরি।', 'High'),
    ],
    ...chapterOneUpgrade,
  },
  {
    id: 'ssc-chapter-2',
    title: 'কম্পিউটার রক্ষণাবেক্ষণ ও সাইবার নিরাপত্তা',
    slug: 'computer-maintenance-cyber-security',
    description: 'কম্পিউটার রক্ষণাবেক্ষণ, ভাইরাস, ম্যালওয়্যার, পাসওয়ার্ড নিরাপত্তা এবং নিরাপদ ইন্টারনেট ব্যবহার।',
    price: 100,
    orderIndex: 2,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 02 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'কম্পিউটার রক্ষণাবেক্ষণ বলতে হার্ডওয়্যার ও সফটওয়্যারকে নিয়মিত পরীক্ষা, পরিষ্কার এবং আপডেট রাখাকে বোঝায়।',
      'সাইবার নিরাপত্তা হলো ডিজিটাল ডিভাইস, নেটওয়ার্ক এবং ডেটাকে অননুমোদিত প্রবেশ, ক্ষতি বা চুরি থেকে রক্ষা করার প্রক্রিয়া।',
      'ভাইরাস ও ম্যালওয়্যার থেকে বাঁচতে অ্যান্টিভাইরাস, সফটওয়্যার আপডেট, শক্তিশালী পাসওয়ার্ড এবং সন্দেহজনক লিংক এড়ানো দরকার।',
      'ব্যাকআপ রাখলে ডেটা হারানোর ঝুঁকি কমে। গুরুত্বপূর্ণ ফাইল ক্লাউড বা আলাদা স্টোরেজে রাখা ভালো।',
    ],
    mcqs: [
      makeMcq('ssc-c2-q1', 'ম্যালওয়্যার কী?', ['ক্ষতিকর সফটওয়্যার', 'শুধু কীবোর্ড', 'ডিসপ্লে ইউনিট', 'ডেটাবেস'], 0, 'Malware হলো malicious software, যা ডিভাইসের ক্ষতি করতে পারে।'),
      makeMcq('ssc-c2-q2', 'শক্তিশালী পাসওয়ার্ডে কোনটি থাকা ভালো?', ['শুধু 123456', 'নাম ও জন্মদিন', 'বড়-ছোট অক্ষর, সংখ্যা ও চিহ্ন', 'একই পাসওয়ার্ড সবখানে'], 2, 'মিশ্র অক্ষর, সংখ্যা ও প্রতীক পাসওয়ার্ডকে শক্তিশালী করে।'),
      makeMcq('ssc-c2-q3', 'ডেটা ব্যাকআপের উদ্দেশ্য কী?', ['ডেটা হারালে পুনরুদ্ধার করা', 'ফাইল মুছে ফেলা', 'ভাইরাস বানানো', 'ইন্টারনেট বন্ধ করা'], 0, 'ব্যাকআপ থাকলে ডেটা হারালেও ফিরিয়ে আনা যায়।'),
      makeMcq('ssc-c2-q4', 'ফিশিং আক্রমণে সাধারণত কী করা হয়?', ['ভুয়া লিংক দিয়ে তথ্য নেওয়া', 'কম্পিউটার পরিষ্কার করা', 'PDF পড়া', 'প্রিন্ট দেওয়া'], 0, 'ফিশিংয়ে ভুয়া ওয়েবসাইট বা বার্তা দিয়ে গোপন তথ্য নেওয়ার চেষ্টা হয়।', 'Hard'),
      makeMcq('ssc-c2-q5', 'অ্যান্টিভাইরাস কেন ব্যবহার করা হয়?', ['ভাইরাস শনাক্ত ও প্রতিরোধে', 'মনিটর উজ্জ্বল করতে', 'ফ্যান চালাতে', 'ইন্টারনেট গতি কমাতে'], 0, 'অ্যান্টিভাইরাস ক্ষতিকর প্রোগ্রাম শনাক্ত করে।'),
      makeMcq('ssc-c2-q6', 'সফটওয়্যার আপডেটের একটি সুবিধা কী?', ['নিরাপত্তা দুর্বলতা ঠিক হয়', 'সব ফাইল মুছে যায়', 'পাসওয়ার্ড দেখা যায়', 'ভাইরাস তৈরি হয়'], 0, 'আপডেট নিরাপত্তা উন্নত করে এবং bug fix করে।'),
    ],
    shortQuestions: [
      makeShort('ssc-c2-s1', 'সাইবার নিরাপত্তা কী?', 'ডিজিটাল তথ্য, ডিভাইস ও নেটওয়ার্ককে অননুমোদিত প্রবেশ বা ক্ষতি থেকে সুরক্ষিত রাখার ব্যবস্থা।', 'High'),
      makeShort('ssc-c2-s2', 'ফিশিং থেকে বাঁচার উপায় লিখ।', 'সন্দেহজনক লিংক না খোলা, URL যাচাই করা, OTP/পাসওয়ার্ড শেয়ার না করা।', 'High'),
      makeShort('ssc-c2-s3', 'কম্পিউটার রক্ষণাবেক্ষণের দুটি কাজ লেখ।', 'ডিস্ক পরিষ্কার রাখা, অ্যান্টিভাইরাস স্ক্যান, সফটওয়্যার আপডেট, ধুলা পরিষ্কার করা।'),
    ],
    ...chapterTwoUpgrade,
  },
  {
    id: 'ssc-chapter-3',
    title: 'ইন্টারনেট ও ওয়েব',
    slug: 'internet-and-web',
    description: 'ইন্টারনেট, ওয়েবসাইট, ব্রাউজার, সার্চ ইঞ্জিন, ই-মেইল এবং অনলাইন যোগাযোগ।',
    price: 100,
    orderIndex: 3,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 03 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'ইন্টারনেট হলো বিশ্বব্যাপী কম্পিউটার নেটওয়ার্কের সমন্বয়, যার মাধ্যমে তথ্য আদান-প্রদান করা যায়।',
      'ওয়েবসাইট হলো নির্দিষ্ট ডোমেইনের অধীনে থাকা ওয়েব পেজের সমষ্টি। ওয়েব ব্রাউজার দিয়ে ওয়েব পেজ দেখা হয়।',
      'সার্চ ইঞ্জিন ব্যবহার করে প্রয়োজনীয় তথ্য খুঁজে পাওয়া যায়। নির্ভরযোগ্য তথ্যের জন্য উৎস যাচাই করা দরকার।',
      'ই-মেইল দ্রুত যোগাযোগের মাধ্যম। subject, recipient, body এবং attachment ই-মেইলের সাধারণ অংশ।',
    ],
    mcqs: [
      makeMcq('ssc-c3-q1', 'ওয়েব পেজ দেখার সফটওয়্যার কোনটি?', ['ব্রাউজার', 'কম্পাইলার', 'স্প্রেডশিট', 'অ্যান্টিভাইরাস'], 0, 'Chrome, Firefox, Edge ইত্যাদি ওয়েব ব্রাউজার।'),
      makeMcq('ssc-c3-q2', 'URL কী নির্দেশ করে?', ['ওয়েব ঠিকানা', 'ফাইলের রং', 'কীবোর্ডের ধরন', 'বিদ্যুৎ সংযোগ'], 0, 'URL হলো Uniform Resource Locator, অর্থাৎ ওয়েব ঠিকানা।'),
      makeMcq('ssc-c3-q3', 'ই-মেইলে ফাইল পাঠাতে কোন অংশ ব্যবহৃত হয়?', ['Attachment', 'Subject', 'CC', 'Inbox'], 0, 'Attachment দিয়ে ফাইল সংযুক্ত করা যায়।'),
      makeMcq('ssc-c3-q4', 'সার্চ ইঞ্জিনের উদাহরণ কোনটি?', ['Google', 'Notepad', 'Paint', 'Calculator'], 0, 'Google একটি সার্চ ইঞ্জিন।', 'Easy'),
      makeMcq('ssc-c3-q5', 'HTTPS-এর S কী বোঝায়?', ['Secure', 'Simple', 'System', 'Search'], 0, 'HTTPS-এ Secure connection থাকে।'),
      makeMcq('ssc-c3-q6', 'ডোমেইন নামের কাজ কী?', ['ওয়েবসাইটের সহজ নাম দেওয়া', 'ডিস্ক ফরম্যাট করা', 'মাউস চালানো', 'স্পিকার বাজানো'], 0, 'ডোমেইন নাম ওয়েবসাইটকে মানুষের পড়ার মতো ঠিকানা দেয়।'),
    ],
    shortQuestions: [
      makeShort('ssc-c3-s1', 'ইন্টারনেট কী?', 'বিশ্বব্যাপী সংযুক্ত নেটওয়ার্কের সমষ্টি যার মাধ্যমে তথ্য আদান-প্রদান করা যায়।', 'High'),
      makeShort('ssc-c3-s2', 'ব্রাউজার ও সার্চ ইঞ্জিনের পার্থক্য লেখ।', 'ব্রাউজার ওয়েব পেজ দেখায়, সার্চ ইঞ্জিন তথ্য খুঁজে পেতে সাহায্য করে।', 'High'),
      makeShort('ssc-c3-s3', 'ই-মেইলের দুটি সুবিধা লিখ।', 'দ্রুত বার্তা পাঠানো যায় এবং ফাইল সংযুক্ত করা যায়।'),
    ],
    ...chapterThreeUpgrade,
  },
  {
    id: 'ssc-chapter-4',
    title: 'লেখালেখি ও হিসাব',
    slug: 'word-processing-and-spreadsheet',
    description: 'ওয়ার্ড প্রসেসিং, ডকুমেন্ট ফরম্যাটিং, স্প্রেডশিট, সূত্র ও হিসাবনিকাশ।',
    price: 100,
    orderIndex: 4,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 04 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'ওয়ার্ড প্রসেসিং সফটওয়্যার দিয়ে লেখা তৈরি, সম্পাদনা, সংরক্ষণ এবং প্রিন্ট করা যায়।',
      'স্প্রেডশিট সফটওয়্যার দিয়ে সারি ও কলামের মাধ্যমে তথ্য সাজানো, হিসাব করা এবং চার্ট তৈরি করা যায়।',
      'Formula সাধারণত equal sign দিয়ে শুরু হয়। যেমন =A1+B1 দুটি cell-এর মান যোগ করে।',
      'ডেটা সাজাতে sort/filter, হিসাব করতে SUM/AVERAGE এবং উপস্থাপনায় chart ব্যবহৃত হয়।',
    ],
    mcqs: [
      makeMcq('ssc-c4-q1', 'ওয়ার্ড প্রসেসরের কাজ কোনটি?', ['ডকুমেন্ট তৈরি', 'ভাইরাস তৈরি', 'হার্ডডিস্ক পোড়ানো', 'নেটওয়ার্ক কেবল বানানো'], 0, 'ওয়ার্ড প্রসেসর দিয়ে লেখা তৈরি ও সম্পাদনা করা যায়।'),
      makeMcq('ssc-c4-q2', 'স্প্রেডশিটে সারি ও কলামের ছেদকে কী বলে?', ['Cell', 'Slide', 'Frame', 'Pixel'], 0, 'সারি ও কলামের মিলিত ঘর হলো cell.'),
      makeMcq('ssc-c4-q3', 'SUM ফাংশনের কাজ কী?', ['যোগফল বের করা', 'ছবি আঁকা', 'ই-মেইল পাঠানো', 'ডেটা মুছে ফেলা'], 0, 'SUM নির্দিষ্ট cell range-এর যোগফল দেয়।'),
      makeMcq('ssc-c4-q4', 'ডকুমেন্টে লেখা মোটা করতে কোন কমান্ড?', ['Bold', 'Italic', 'Underline', 'Sort'], 0, 'Bold কমান্ড লেখা মোটা করে।', 'Easy'),
      makeMcq('ssc-c4-q5', 'স্প্রেডশিটে সূত্র সাধারণত কোন চিহ্ন দিয়ে শুরু হয়?', ['=', '+', '#', '@'], 0, 'Formula equal sign দিয়ে শুরু হয়।'),
      makeMcq('ssc-c4-q6', 'ডেটা visualভাবে দেখাতে কোনটি বেশি উপযোগী?', ['Chart', 'Caps Lock', 'Recycle Bin', 'Wallpaper'], 0, 'চার্ট ডেটা সহজে বোঝাতে সাহায্য করে।'),
    ],
    shortQuestions: [
      makeShort('ssc-c4-s1', 'ওয়ার্ড প্রসেসিং কী?', 'কম্পিউটারে লেখা তৈরি, সম্পাদনা, সংরক্ষণ ও প্রিন্ট করার প্রক্রিয়া।'),
      makeShort('ssc-c4-s2', 'Cell কী?', 'স্প্রেডশিটে row ও column-এর ছেদে তৈরি ঘরকে cell বলে।', 'High'),
      makeShort('ssc-c4-s3', 'Formula ও Function-এর পার্থক্য লেখ।', 'Formula ব্যবহারকারী তৈরি করে; Function হলো আগে থেকে তৈরি নির্দিষ্ট হিসাবের কমান্ড।', 'High'),
    ],
    ...chapterFourUpgrade,
  },
  {
    id: 'ssc-chapter-5',
    title: 'মাল্টিমিডিয়া ও গ্রাফিক্স',
    slug: 'multimedia-and-graphics',
    description: 'মাল্টিমিডিয়া উপাদান, ছবি/অডিও/ভিডিও, গ্রাফিক্স ফরম্যাট এবং ডিজিটাল কনটেন্ট।',
    price: 100,
    orderIndex: 5,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 05 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'মাল্টিমিডিয়া হলো text, image, audio, video, animation ইত্যাদি উপাদানের সমন্বিত ব্যবহার।',
      'ডিজিটাল ছবিতে pixel হলো ক্ষুদ্রতম একক। resolution যত বেশি হয়, ছবি তত স্পষ্ট হতে পারে।',
      'Image format হিসেবে JPG, PNG, GIF, SVG ব্যবহৃত হয়। প্রয়োজন অনুযায়ী format নির্বাচন করতে হয়।',
      'মাল্টিমিডিয়া শিক্ষা, বিজ্ঞাপন, বিনোদন, প্রশিক্ষণ ও online communication-এ ব্যাপকভাবে ব্যবহৃত হয়।',
    ],
    mcqs: [
      makeMcq('ssc-c5-q1', 'মাল্টিমিডিয়ার উপাদান কোনটি?', ['অডিও', 'শুধু CPU', 'শুধু RAM', 'মাদারবোর্ড'], 0, 'Audio multimedia-এর একটি উপাদান।'),
      makeMcq('ssc-c5-q2', 'ডিজিটাল ছবির ক্ষুদ্রতম একক কী?', ['Pixel', 'Cell', 'Byte', 'Folder'], 0, 'Pixel ছবির ক্ষুদ্রতম দৃশ্যমান একক।'),
      makeMcq('ssc-c5-q3', 'স্বচ্ছ background-এর জন্য কোন image format বেশি ব্যবহৃত?', ['PNG', 'TXT', 'MP3', 'DOCX'], 0, 'PNG transparency support করে।'),
      makeMcq('ssc-c5-q4', 'ভিডিও কোন ধরনের কনটেন্ট?', ['মাল্টিমিডিয়া', 'শুধু টেক্সট', 'শুধু সংখ্যা', 'শুধু ফোল্ডার'], 0, 'ভিডিওতে ছবি ও শব্দ থাকতে পারে, তাই এটি multimedia content.'),
      makeMcq('ssc-c5-q5', 'Animation কী?', ['ক্রমাগত পরিবর্তিত ছবি দিয়ে motion তৈরি', 'শুধু hard disk', 'একটি স্থির সংখ্যা', 'printer queue'], 0, 'Animation চলমান ভিজ্যুয়াল প্রভাব তৈরি করে।'),
      makeMcq('ssc-c5-q6', 'JPG সাধারণত কোন কাজে ব্যবহৃত হয়?', ['ফটোগ্রাফ সংরক্ষণ', 'প্রোগ্রাম চালানো', 'পাসওয়ার্ড এনক্রিপ্ট', 'সাউন্ড রেকর্ড'], 0, 'JPG ছবি সংকুচিত করে সংরক্ষণে জনপ্রিয়।'),
    ],
    shortQuestions: [
      makeShort('ssc-c5-s1', 'মাল্টিমিডিয়া কী?', 'একাধিক media যেমন লেখা, ছবি, অডিও, ভিডিও ও animation-এর সমন্বিত ব্যবহার।', 'High'),
      makeShort('ssc-c5-s2', 'Pixel কী?', 'ডিজিটাল ছবির ক্ষুদ্রতম একককে pixel বলে।', 'High'),
      makeShort('ssc-c5-s3', 'PNG-এর একটি সুবিধা লিখ।', 'PNG transparent background support করে এবং quality ভালো রাখে।'),
    ],
    ...chapterFiveUpgrade,
  },
  {
    id: 'ssc-chapter-6',
    title: 'প্রোগ্রামিং এর মাধ্যমে সমস্যার সমাধান',
    slug: 'problem-solving-with-programming',
    description: 'সমস্যা বিশ্লেষণ, অ্যালগরিদম, ফ্লোচার্ট, ভেরিয়েবল, ইনপুট-আউটপুট এবং প্রোগ্রামিং ধারণা।',
    price: 100,
    orderIndex: 6,
    isPublished: true,
    freePreviewEnabled: true,
    pdfTitle: 'Chapter 06 Smart PDF Notes',
    previewPageLimit: 2,
    pdfPages: [
      'প্রোগ্রামিং হলো নির্দিষ্ট সমস্যা সমাধানের জন্য কম্পিউটারকে ধাপে ধাপে নির্দেশনা দেওয়ার প্রক্রিয়া।',
      'অ্যালগরিদম হলো সমস্যা সমাধানের ধাপসমূহের যৌক্তিক তালিকা। ফ্লোচার্ট চিহ্নের মাধ্যমে অ্যালগরিদম দেখায়।',
      'Variable ডেটা সংরক্ষণ করে। Input নেওয়া, process করা এবং output দেওয়া প্রোগ্রামের সাধারণ ধাপ।',
      'সমস্যা সমাধানে প্রথমে সমস্যা বোঝা, তারপর algorithm তৈরি, এরপর coding ও testing করা ভালো পদ্ধতি।',
    ],
    mcqs: [
      makeMcq('ssc-c6-q1', 'অ্যালগরিদম কী?', ['সমস্যা সমাধানের ধাপ', 'মনিটরের রং', 'ফাইলের নাম', 'ইন্টারনেট স্পিড'], 0, 'Algorithm হলো step-by-step solution plan.'),
      makeMcq('ssc-c6-q2', 'ফ্লোচার্টে সিদ্ধান্ত বোঝাতে কোন আকৃতি ব্যবহৃত হয়?', ['Diamond', 'Oval', 'Rectangle', 'Circle'], 0, 'Decision symbol সাধারণত diamond shape.'),
      makeMcq('ssc-c6-q3', 'Variable-এর কাজ কী?', ['ডেটা সংরক্ষণ করা', 'মনিটর পরিষ্কার করা', 'কেবল যুক্ত করা', 'প্রিন্ট বন্ধ করা'], 0, 'Variable program-এর data temporarily রাখে।'),
      makeMcq('ssc-c6-q4', 'Program testing কেন দরকার?', ['ভুল খুঁজে ঠিক করতে', 'ডেটা লুকাতে', 'কম্পিউটার বন্ধ করতে', 'স্ক্রিন ছোট করতে'], 0, 'Testing করলে program ঠিকমতো কাজ করছে কিনা বোঝা যায়।'),
      makeMcq('ssc-c6-q5', 'Input-Process-Output মডেলে process-এর কাজ কী?', ['ডেটা প্রক্রিয়াকরণ', 'শুধু ফল দেখানো', 'শুধু ডেটা নেওয়া', 'কম্পিউটার বিক্রি করা'], 0, 'Process input ডেটা থেকে ফলাফল তৈরি করে।'),
      makeMcq('ssc-c6-q6', 'Loop ব্যবহার করা হয় কেন?', ['পুনরাবৃত্ত কাজ করতে', 'মাউস বদলাতে', 'ফাইল rename করতে', 'speaker বাড়াতে'], 0, 'একই কাজ বারবার করতে loop ব্যবহৃত হয়।', 'Hard'),
    ],
    shortQuestions: [
      makeShort('ssc-c6-s1', 'প্রোগ্রামিং কী?', 'সমস্যা সমাধানের জন্য কম্পিউটারকে নির্দিষ্ট ভাষায় নির্দেশনা দেওয়ার প্রক্রিয়া।', 'High'),
      makeShort('ssc-c6-s2', 'অ্যালগরিদম ও ফ্লোচার্টের পার্থক্য লেখ।', 'অ্যালগরিদম ধাপগুলো লিখিতভাবে প্রকাশ করে; ফ্লোচার্ট প্রতীক দিয়ে ধাপগুলো দেখায়।', 'High'),
      makeShort('ssc-c6-s3', 'Variable কেন ব্যবহার করা হয়?', 'প্রোগ্রামে ডেটা সংরক্ষণ ও ব্যবহারের জন্য variable ব্যবহৃত হয়।'),
    ],
    ...chapterSixUpgrade,
  },
];

export const defaultSscIctConfig: SscIctConfig = {
  chapters: defaultSscChapters,
  packagePlan: {
    id: 'ssc-ict-full-package',
    title: 'SSC ICT Complete Package',
    description: 'All chapter PDFs, MCQ practice, quiz exams, dashboard, leaderboard and result sharing.',
    price: 499,
    compareAtPrice: 600,
    isPublished: true,
  },
  quizSettings: {
    durationMinutes: 25,
    totalQuestions: 25,
    negativeMarkingEnabled: false,
    negativeMarkValue: 0.25,
    leaderboardEnabled: true,
  },
  updatedAt: new Date(0).toISOString(),
};
